apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eureka-hpa-cpu
  labels:
    env: development
    tier: backend
    app: eureka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eureka-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
