apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    env: development
    tier: backend
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      env: development
      tier: backend
      app: eureka
  template:
    metadata:
      labels:
        env: development
        tier: backend
        app: eureka
    spec:
      containers:
        - name: eureka
          image: contest20-container-registry.kr.ncr.ntruss.com/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: config  # ConfigMap에서 TZ 값을 가져옴
                  key: TZ
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
