apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    env: development
    tier: backend
    app: member-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    env: development
    tier: backend
    app: member-service