apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: report-service-hpa-cpu
  labels:
    env: development
    tier: backend
    app: report-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: report-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
