apiVersion: v1
kind: Service
metadata:
  name: report-service
  labels:
    env: development
    tier: backend
    app: report-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    env: development
    tier: backend
    app: report-service
