apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plogging-service-hpa-cpu
  labels:
    env: development
    tier: backend
    app: plogging-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plogging-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
