apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    env: development
    tier: backend
    app: apigateway
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    env: development
    tier: backend
    app: apigateway
